### PR TITLE
UI & other improvements in Admin project

### LINKED ISSUE #290: Admin styling & UX improvements
- [x] align processor cards vertically (test with more than 3)
- [x] improve button style (relates to #276)
- [x] improve button style in change password
- [x] improve button style in register user
- [x] setup toast to show from top center
- [x] fix issue with internal fetch showing errors two times
- [x] fix [chart issue](https://github.com/ClearGDPR/ClearGDPR/pull/282#issuecomment-404299981)
- [x] fix issue with pre-commit hook braking the code style
- [ ] use new action bar from Juan
- [ ] use new button styles from Juan

The cards should not appear one below the other and we need to improve delete button styling:

Horizontal line-up
screen shot 2018-07-12 at 15 34 52

That's how it should be:
screen shot 2018-07-12 at 15 35 05

Change password form button:
screen shot 2018-07-12 at 15 39 17

Wrong toasts:
screen shot 2018-07-12 at 15 42 16

Double error toast:
screen shot 2018-07-12 at 15 43 32

### PR DESCRIPTION
**Pull request by maksymilian-majer**
See details on what's implemented in #290.
Closes #290.

### CODE REVIEW

File: admin/src/components/Processors/Processors.js [hunk 1]
```diff
@@ -25,6 +26,21 @@ const Processors = ({
     onDeleteProcessorClick(processor);
   }
 
+  let renderProcessors = function() {
```
Comment (fjcero) [inline admin/src/components/Processors/Processors.js]: `const`

File: admin/src/components/Processors/EditProcessor.js [hunk 2]
```diff
@@ -79,9 +79,9 @@ export class EditProcessor extends React.Component {
 }
 
 const EditProcessorForm = props => {
-  const { errors, values, ...formProps } = props;
+  const { errors, values, isLoading, ...formProps } = props;
```
Comment (fjcero) [inline admin/src/components/Processors/EditProcessor.js]: 👍

Comment (maksymilian-majer) [reply admin/src/components/Processors/EditProcessor.js]: Yeah, that was causing console errors when passing `formProps` down
