### PR TITLE
Subjects data status on new processor created

### LINKED ISSUE #337: Don't redirect if request fails
**Describe the bug**
The new processors does not have an address, so the request fails. Currently the request fails, but user is still redirected. The subject does not exist. @fjcero Please complete or modify.

**To Reproduce**
1. login to admin.
2. add a new processor.
3. login to front-end demo.
4. consent to all processors.

**Expected behavior**
We should handle error gracefully and show some error message.

**Screenshots**
None.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by fjcero**
Fixes #337 

## Proposed Changes
- Removed console.log
- Some styling to the current subject's data status
- Fixed issues on displaying new processors in subject's data status

### CODE REVIEW

File: frontend/src/Elements/components/Portability/UserData.js [hunk 1]
```diff
@@ -23,8 +23,8 @@ class UserData extends React.PureComponent {
 
     if (processors && status.processors) {
       processorsList = processors.map(p => {
-        const s = _.find(status.processors, { id: p.id });
-        p.status = SUBJECT_DATA_STATUS[s.status];
+        const s = _.find(status.processors, { id: p.id }) || {};
+        p.status = s.status ? SUBJECT_DATA_STATUS[s.status] : 'Unconsented';
```
Comment (segoddnja) [inline frontend/src/Elements/components/Portability/UserData.js]: I think it makes sense to move processors decoration to Subject context and do it only once - when fetch processors.

Comment (fjcero) [reply frontend/src/Elements/components/Portability/UserData.js]: I like the idea, will do it!

File: frontend/src/Elements/theme/SubjectData.scss [hunk 2]
```diff
@@ -2,6 +2,10 @@
 
 .data {
   .processor {
+    border: 1px solid rgba(0,0,0,0.1);
```
Comment (Nelrohd) [inline frontend/src/Elements/theme/SubjectData.scss]: gonna be picky but should we use variable for colours?
